apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"argoproj.io/v1alpha1","kind":"Application","metadata":{"annotations":{},"finalizers":["resources-finalizer.argocd.argoproj.io"],"name":"infra-database","namespace":"argocd"},"spec":{"destination":{"namespace":"database","server":"https://kubernetes.default.svc"},"project":"default","source":{"path":"infra/database","repoURL":"git@github.com:Cozm1n1412/k3s-gitops-infra.git","targetRevision":"main"},"syncPolicy":{"automated":{"prune":true,"selfHeal":true},"syncOptions":["CreateNamespace=true"]}}}
  creationTimestamp: "2026-08-29T12:59:28Z"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  generation: 9
  name: infra-database
  namespace: argocd
  resourceVersion: "6293"
  uid: f7ea8ee8-c1ab-4e40-a930-fd982e580008
spec:
  destination:
    namespace: database
    server: https://kubernetes.default.svc
  project: default
  source:
    path: infra/database
    repoURL: git@github.com:Cozm1n1412/k3s-gitops-infra.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
status:
  controllerNamespace: argocd
  health:
    lastTransitionTime: "2026-08-29T12:59:30Z"
    status: Healthy
  history:
  - deployStartedAt: "2026-08-29T12:59:30Z"
    deployedAt: "2026-08-29T12:59:32Z"
    id: 0
    initiatedBy:
      automated: true
    revision: 8fdba8ef1694d47b7aa947f858edc292cbcb092e
    source:
      path: infra/database
      repoURL: git@github.com:Cozm1n1412/k3s-gitops-infra.git
      targetRevision: main
  operationState:
    finishedAt: "2026-08-29T12:59:32Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        automated: true
      retry:
        limit: 5
      sync:
        prune: true
        revision: 8fdba8ef1694d47b7aa947f858edc292cbcb092e
        source:
          path: infra/database
          repoURL: git@github.com:Cozm1n1412/k3s-gitops-infra.git
          targetRevision: main
        syncOptions:
        - CreateNamespace=true
    phase: Succeeded
    startedAt: "2026-08-29T12:59:30Z"
    syncResult:
      resources:
      - group: ""
        hookPhase: Running
        kind: Namespace
        message: namespace/database configured
        name: database
        namespace: database
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Secret
        message: secret/postgres-secrets configured
        name: postgres-secrets
        namespace: database
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/postgres-db configured
        name: postgres-db
        namespace: database
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        images:
        - postgres:16-alpine
        kind: StatefulSet
        message: statefulset.apps/postgres configured
        name: postgres
        namespace: database
        status: Synced
        syncPhase: Sync
        version: v1
      revision: 8fdba8ef1694d47b7aa947f858edc292cbcb092e
      source:
        path: infra/database
        repoURL: git@github.com:Cozm1n1412/k3s-gitops-infra.git
        targetRevision: main
  reconciledAt: "2026-08-29T12:59:33Z"
  resourceHealthSource: appTree
  resources:
  - kind: Namespace
    name: database
    status: Synced
    version: v1
  - kind: Secret
    name: postgres-secrets
    namespace: database
    status: Synced
    version: v1
  - kind: Service
    name: postgres-db
    namespace: database
    status: Synced
    version: v1
  - group: apps
    kind: StatefulSet
    name: postgres
    namespace: database
    status: Synced
    version: v1
  sourceHydrator: {}
  sourceType: Directory
  summary:
    images:
    - postgres:16-alpine
  sync:
    comparedTo:
      destination:
        namespace: database
        server: https://kubernetes.default.svc
      source:
        path: infra/database
        repoURL: git@github.com:Cozm1n1412/k3s-gitops-infra.git
        targetRevision: main
    revision: 8fdba8ef1694d47b7aa947f858edc292cbcb092e
    status: Synced
