apiVersion: v1
kind: Service
metadata:
  name: redis-core
  namespace: telemetry
  labels:
    app: redis-core
spec:
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  selector:
    app: redis-core
